let product = [
  {
    name: "Đĩa Than Bằng Kiều - Mắt Biếc",
    caretory: "New LP",
    singer: "Bằng Kiều",
    price: 1200000,
    des:"Đĩa than chọn loc 8 ca khúc do Bằng Kiều trình bày. Bản 180 Vinyl , made in germany",
    pic:"bangkieu.jpg",
    list: [
      "1. Rồi mai tôi đưa em",
      "2. Hạ trắng",
      "3. Dấu tình sầu",
      "4. Phôi pha",
      "5. Mắt biếc",
      "6. Bài không tên số 2",
      "7. Thu hát cho người",
      "8. Lệ đá",
    ],
  },
  {
    name: "Đĩa than Bảo Yến The Best",
    caretory: "New LP",
    singer: "Bảo Yến",
    price: 1200000,
    des: "Đĩa than chọn lọc 10 ca khúc trữ tình do Bảo Yến trình bày. Bản 180g High Quality Vinyl, Made in germany",
    pic:"baoyen.jpg",
    list: [
      "1A. THOI THE THI CHIA TAY",
      "2A. KHUC THUY DU",
      "3A. CHUYEN HOP TAN",
      "4A. TRONG CUOC TINH AN HAN",
      "5A. ANH CON NO EM",
      "1B. CHUYEN BA NGUOI",
      "2B. BIET DEN BAO GIO",
      "3B. CHIEC LA CUOI CUNG",
      "4B. CHIEU HA VANG",
      "5B. COI MONG",
    ],
  },
  {
    name: "Đĩa than Chế Linh - Giọt Lệ Sầu",
    caretory: "New LP",
    singer: "Chế Linh",
    price: 1200000,
    des:"Đĩa than với phần trình bày của danh ca Chế Linh, bản 180g High Quality Vinyl - Made in Germany",
    pic:"chelinh-giotlesau.jpg",
    list: [
      "1A. GIOT LE SAU",
      "2A. MOT LAN CUOI",
      "3A. TINH PHU",
      "4A. MUOI NAM TINH CU",
      "1B. HAN TINH",
      "2B. TINH CHET THEO MUA DONG",
      "3B. NGHEN NGAO",
      "4B. THANH PHO MUA BAY",
      "5B. LOI CUOI CHO NGUOI TINH PHU",
    ],
  },
  {
    name: "Đĩa than Chuyện Hẹn Hò",
    singer: "Nhiều ca sĩ",
    caretory: "New LP",
    price: 1000000,
    des: "Đĩa than gồm 08 ca khúc trữ tình với phần trình bày của 02 ca sĩ Hương Lan và Thái Châu",
    pic:"chuyenhenho.jpg",
    list: [
      "1. Chuyện hẹn hò - Hương Lan & Thái Châu",
      "2. Thu sầu - Thái Châu",
      "3. Sầu lẻ bóng - Hương Lan ",
      "4. Đà lạt hoàng hôn - Thái Châu ",
      "1. Không bao giờ quên anh - Hương Lan ",
      "2. Tà áo cưới - Thái Châu",
      "3. Nỗi buồn hoa phượng - Hương Lan ",
      "4. Đường xưa lối cũ - Hương Lan & Thái Châu",
    ],
  },
  {
    name: "Đĩa than Duy Khánh - Đập Vỡ Cây Đàn",
    caretory: "New 100%",
    singer: " Duy Khánh",
    price: 1200000,
    des:"Đĩa than chọn lọc 8 ca khúc do Duy Khánh trình bày, Bản 180 Vinyl-made in germany",
    pic:"duykhanh.jpg",
    list: [
      "1. Đập vỡ cây đàn",
      "2. Lời đắng cho cuộc tình",
      "3. Qua cơn mê",
      "4. Trường cũ tình xưa",
      "5. Thương về miền Trung",
      "6. Những chiều không có em",
      "7. Linh hồn tượng đá",
      "8. Mưa trên phố Huế",
    ],
  },
  {
    name: "Đĩa than Đức Tuấn - Phạm Duy",
    caretory: "New LP",
    singer: "Phạm Duy",
    price: 800000,
    des:"Đĩa than Đức Tuấn - Phạm Duy là lời tưởng niệm, lời tri ân sau cuối của Đức Tuấn dành cho nhạc sĩ Phạm Duy. Không gì hơn là bài hát lại là những lời ca tràn ngập niềm vui cuộc sống và bình thản nhìn về cõi thiên thu của ông để tưởng nhớ một con người vĩ đại trong tim Đức Tuấn",
    pic:"ductuan-phamduy.jpg",
    list: [
      "01. Intro",
      "02. Tình Kỹ Nư",
      "03. Nếu Một Mai Em Sẽ Qua Đời",
      "04. Con Quỳ Lạy Chúa Trên Trời",
      "05. Mùa Thu Chết",
      "06. Còn Gì Nữa Đâu",
      "07. Đừng Bỏ Em Một Mình",
      "08. Nắng Chiều Rực Ro",
      "09. Đường Chiều Lá Rụng",
      "10. Những Gì Đem Theo Vào Cõi Chết",
      "11. Outtro",
    ],
  },
];

let user = [
  {
    name: "Thành",
    old: 24,
    gmail: "dotienthanh96hn@gmail.com",
    usename: "thanhgadk123",
    pass: "thanh123",
  },
];
